version: 2.1
orbs:
  node: circleci/node@5.0.2
  render: circleci/render@volatile  # Use "volatile" to get the latest version

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: nest build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: render/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: render deploy -- --force

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
