version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:18.16.0.
    steps:
      - checkout
      - run:
          name: Install Node.js packages
          command: yarn install --frozen-lockfile
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Render
          command: |
            # Add Render deployment commands here
            # Example:
            curl -H "Authorization: Bearer rnd_1hlhEHqdZugHinjzI86HRE06RwlA" -X POST https://api.render.com/v1/services/my-service/deploy

workflows:
  version: 2
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
