version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14.17.1

    steps:
      - checkout
      - run:
          name: Install Node.js using yarn
          command: |
            yarn global add n
            export PATH="$(yarn global bin):$PATH"
            n latest
      - run:
          name: Install Dependencies and Build
          command: |
            yarn install --frozen-lockfile
            yarn test
            yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:14.17.1

    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Render
          command: |
            # Add Render deployment commands here
            # Example:
            curl -H "Authorization: Bearer rnd_1hlhEHqdZugHinjzI86HRE06RwlA" -X POST https://api.render.com/v1/services/my-service/deploy

workflows:
  version: 2
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
