version: 2.1

jobs:
 build:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: node:20
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Render
          command: |
            # Add Render deployment commands here
            # Example:
            curl -H "Authorization: Bearer rnd_1hlhEHqdZugHinjzI86HRE06RwlA" -X POST https://api.render.com/v1/services/my-service/deploy

workflows:
  version: 2
  test_my_app:
    jobs:
      -build
      - deploy:
          requires:
            -build
          filters:
            branches:
              only: main
